INSERT INTO artist (name) VALUES ('Marvin Gaye');
INSERT INTO artist (name) VALUES ('The Beach Boys');
INSERT INTO artist (name) VALUES ('Joni Mitchell');
INSERT INTO artist (name) VALUES ('Stevie Wonder');
INSERT INTO artist (name) VALUES ('The Beatles');
INSERT INTO artist (name) VALUES ('Nirvana');
INSERT INTO artist (name) VALUES ('Fleetwood Mac');
INSERT INTO artist (name) VALUES ('Prince and the Revolution');
INSERT INTO artist (name) VALUES ('Bob Dylan');
INSERT INTO artist (name) VALUES ('Lauryn Hill');

INSERT INTO album (artist_id, name, song_count, year_released) VALUES (1, 'What`s Going On', 9, 1971);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (2, 'Pet Sounds', 13, 1966);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (3, 'Blue', 10, 1971);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (4, 'Songs in the Key of Life', 21, 1976);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (5, 'Abbey Road', 17, 1969);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (6, 'Nevermind', 12, 1991);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (7, 'Rumours', 11, 1977);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (8, 'Purple Rain', 9, 1984);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (9, 'Blood on the Tracks', 10, 1975);
INSERT INTO album (artist_id, name, song_count, year_released) VALUES (10, 'The Miseducation of Lauryn Hill', 16, 1998);